import React from 'react'
import { ToastContainer, toast } from 'react-toastify';
import { useRef, useState, useEffect } from 'react'
import { v4 as uuidv4 } from "uuid";

const Manager = () => {


    //state to toggle password field between text and password. visibility on off
    // 1.usestate use gareko solution
    // const [showpass, setshowpass] = useState('true').           yo chai input ma halnu paryo yo step use garna----> type={showpass? "text":"password"}
    //2useref use gareko solution
    const passRef = useRef()

    //state for the form data
    const [form, setform] = useState({
        site: "",
        username: "",
        password: ""
    })

    //state for the password array
    const [passwordArray, setPasswordArray] = useState([])

    //ref to the eye icon to toggle the password visibility
    const ref = useRef(0)

    const getPassword = async () => {
        let req = await fetch("http://localhost:3000/", {})
        let passwords = await req.json();
        let passwordArray;
        console.log(passwords)
        setPasswordArray(passwords)

    }


    //checking if there are any passwords in local storage and if there are then set it to the password array state
    useEffect(() => {
getPassword();

    }, [])

    //saving the password to the password array state and also to the local storage
    const savePassword = async() => {
        if (form.site.length > 3 && form.username.length > 3 && form.password.length > 5) {

            setPasswordArray([...passwordArray, { ...form, id: uuidv4() }]) // yo line le password array ma form ko data halxa with a unique id generated by uuidv4
            setform({ site: "", username: "", password: "" }) // form lai empty garne save garda
            
            let res=await fetch("http://localhost:3000/", {method:"POST", headers: {'Content-Type': 'application/json'}, body: JSON.stringify({...form, id: uuidv4()})})

            console.log([...passwordArray, { ...form, id: uuidv4() }])
            toast('Password saved successfully!', {
                position: "top-right",
                autoClose: 5000,
                hideProgressBar: false,
                closeOnClick: false,
                pauseOnHover: true,
                draggable: true,
                progress: undefined,
                theme: "dark",

            });
        }// yo line le check garxa ki form ko site, username and password field ma 3 character bhanda badi xa ki nai. yo validation le user lai thap secure password rakhna encourage garxa and also avoid saving empty or very short passwords.
        else {
            toast('Please fill all fields with valid data!', {
                position: "top-right",
                autoClose: 5000,
                hideProgressBar: false,
                closeOnClick: false,
                pauseOnHover: true,
                draggable: true,
                progress: undefined,
                theme: "dark",
            });
        }

    }

    //to delete the password
    const deletePassword = async (id) => {
        console.log("deleting the password with id", id)
        let c = confirm("Are you sure you want to delete this password?")
        if (c) {

            setPasswordArray(passwordArray.filter(item => item.id !== id)) // yo line le password array bata tyo password lai hatauxa . kinaki filter le tyo id vaala item lai hatauxa and baki sab lai rakhxa new array ma and tyo new array le setPasswordArray garxa
            let res=await fetch("http://localhost:3000/", {method:"DELETE", headers: {'Content-Type': 'application/json'}, body: JSON.stringify({id })})
            toast('Password deleted!', {
                position: "top-right",
                autoClose: 5000,
                hideProgressBar: false,
                closeOnClick: false,
                pauseOnHover: true,
                draggable: true,
                progress: undefined,
                theme: "dark",

            });
        }

    }
    //to edit password
    const editPassword = async (id) => {
        console.log("editing the password with id", id)
        setform(passwordArray.filter(i => i.id === id)[0]) //edit garni password ko data form ma halxa tesaile filter gareko. filter le tyo id vaala item lai rakxa and baki sab lai hatauxa new array ma and [0] le tyo item lai form ma halxa kina ki filter le array return garxa
        let res=await fetch("http://localhost:3000/", {method:"DELETE", headers: {'Content-Type': 'application/json'}, body: JSON.stringify({id })})
            
        setPasswordArray(passwordArray.filter(item => item.id !== id)) // yo line le edit garna lageko password lai delete gardinxa password array bata . yo garena vane same password ko 2 ota entry hunxa. ek edit mode ma halera and ek original form ma

    }
    //IMPORTANT Developer THING TO CONSIDER 
    // ani arko logic ---> hamle jaile ni edit garni bela , save button click nagare samma editPassword vitra localstorage lai update garnu hudaina. kinaki kaile kai user ley edit buttin thichera website banda ghardina sakxa. tesko lagi hamle data bachauna parxa tyo data lai state ma halera rakhna parxa. ani save button click garda tyo data lai local storage ma halna parxa.

    //function to handle the change in the form inputs and set the form state accordingly
    const handleChange = (e) => {
        setform({ ...form, [e.target.name]: e.target.value })
    }


    //function to toggle the password visibility by changing the src of the eye icon
    const showPassword = () => {
        //   alert("show the password")
        if (ref.current.src.includes("eye.png")) {
            ref.current.src = "hidden.png"
            passRef.current.type = "text" //solution 2 ref wala
            // setshowpass(!showpass) solution 1 state wala
        }
        else {
            ref.current.src = "eye.png"
            passRef.current.type = "password" //solution 2
            // setshowpass(!showpass) solution 1
        }
    }

    const copyText = (text) => {
        toast('Copied to clipboard!', {
            position: "top-right",
            autoClose: 5000,
            hideProgressBar: false,
            closeOnClick: false,
            pauseOnHover: true,
            draggable: true,
            progress: undefined,
            theme: "dark",

        });
        navigator.clipboard.writeText(text)
    }






    return (
        <>
            <ToastContainer
                position="top-right"
                autoClose={5000}
                hideProgressBar={false}
                newestOnTop={false}
                closeOnClick={false}
                rtl={false}
                pauseOnFocusLoss
                draggable
                pauseOnHover
                theme="dark"

            />
            <div className="absolute inset-0 -z-10 h-full w-full bg-green-50 bg-[linear-gradient(to_right,#8080800a_1px,transparent_1px),linear-gradient(to_bottom,#8080800a_1px,transparent_1px)] bg-[size:14px_24px]"><div className="absolute left-0 right-0 top-0 -z-10 m-auto h-[310px] w-[310px] rounded-full bg-green-400 opacity-20 blur-[100px]"></div></div>

            <div className="p-3 md:mycontainer min-h-[89vh]">
                <h1 className='text-4xl font-bold text-center'>
                    <span className='text-green-500'>&lt;</span>
                    Pass
                    <span className='text-green-500'>OP/&gt;</span>
                </h1>
                <p className='text-green-900 text-lg text-center'>Your own password manager</p>
                <div className="flex flex-col p-4 text-black gap-8 items-center ">
                    {/* website input */}
                    <input value={form.site} onChange={handleChange} className='bg-white rounded-full w-full w-32 border border-white p-4 py-1' type="text" placeholder='Enter Website URL' name='site' />
                    <div className="flex flex-col md:flex-row w-full justify-around gap-8">
                        {/* username input */}
                        <input value={form.username} onChange={handleChange} className='bg-white rounded-full w-full w-32 border border-white p-4 py-1' type="text" placeholder='Enter Username' name='username' />
                        <div className="relative">
                            {/* password input */}
                            <input ref={passRef} type='password' value={form.password} onChange={handleChange} className='bg-white rounded-full w-full w-32 border border-white p-4 py-1' placeholder='Enter Password' name='password' />
                            <span className="absolute right-0 top-0.5 cursor-pointer" onClick={showPassword}>
                                <img ref={ref} className='p-1' src="eye.png" alt="eyeee" width={30} />
                            </span>
                        </div>
                    </div>
                    <button onClick={savePassword} className='flex w-32 border border-white justify-center items-center bg-green-600 hover:bg-green-500 rounded-full px-8 py-2 w-fit gap-2'>
                        <lord-icon
                            src="https://cdn.lordicon.com/efxgwrkc.json"
                            trigger="hover"
                        >
                        </lord-icon>
                        Save Password
                    </button>
                </div>

                <div className="passwords">
                    <h2 className='text-2xl font-bold text-green-500 py-4'>Stored Passwords</h2>
                    {
                        passwordArray.length === 0 && <div>No passwords to show</div>
                    }
                    {
                        passwordArray.length != 0 && <table className="table-auto w-full rounded-md overflow-hidden mb-10">
                            <thead className='bg-green-500 text-white'>
                                <tr>
                                    <th className='py-3'>Website</th>
                                    <th className='py-2'>Username</th>
                                    <th className='py-2'>Password</th>
                                    <th className='py-2'>Actions</th>
                                </tr>
                            </thead>
                            <tbody className='text-center bg-green-100'>
                                {
                                    passwordArray.map((item, index) => {

                                        return <tr key={index}>


                                            <td className='  border border-white p-3'>
                                                <div className="flex items-center justify-center">
                                                    <span><a className='hover:text-green-500 hover:underline textoverflow' href={item.site} target='_blank'>
                                                        {item.site}</a></span>
                                                    <div className='lordiconcopy size-7 cursor-pointer' onClick={() => { copyText(item.site) }}>

                                                        <lord-icon
                                                            style={{ "width": "20px", "height": "20px", "padding": "4px" }}
                                                            src="https://cdn.lordicon.com/xuoapdes.json"
                                                            trigger="hover"
                                                        >
                                                        </lord-icon>
                                                    </div>
                                                </div>
                                            </td>

                                            <td className='   border border-white p-2'>
                                                <div className="flex items-center justify-center">
                                                    {item.username}
                                                    <div className='lordiconcopy size-7 cursor-pointer ' onClick={() => { copyText(item.username) }}>

                                                        <lord-icon
                                                            style={{ "width": "20px", "height": "20px", "padding": "4px" }}
                                                            src="https://cdn.lordicon.com/xuoapdes.json"
                                                            trigger="hover"
                                                        >
                                                        </lord-icon>
                                                    </div>
                                                </div>


                                            </td>
                                            <td className='  border border-white p-2'>
                                                <div className="flex items-center justify-center">
                                                    {"*".repeat(item.password.length)}
                                                    <div className='lordiconcopy size-7 cursor-pointer' onClick={() => { copyText(item.password) }} >
                                                        {/* copy icon */}
                                                        <lord-icon
                                                            style={{ "width": "20px", "height": "20px", "padding": "4px" }}
                                                            src="https://cdn.lordicon.com/xuoapdes.json"
                                                            trigger="hover"
                                                        >
                                                        </lord-icon>
                                                    </div>
                                                </div>
                                            </td>

                                            <td className='  border border-white p-2'>
                                                {/* edit button */}
                                                <span className='cursor-pointer mx-1' onClick={() => { editPassword(item.id) }} >

                                                    <lord-icon
                                                        style={{ "width": "20px", "height": "20px", "padding": "4px" }}
                                                        src="https://cdn.lordicon.com/umuwriak.json"
                                                        trigger="hover"
                                                    >
                                                    </lord-icon>
                                                </span>

                                                {/* delete button */}
                                                <span className='cursor-pointer mx-1' onClick={() => { deletePassword(item.id) }}>

                                                    <lord-icon
                                                        style={{ "width": "20px", "height": "20px", "padding": "4px" }}
                                                        src="https://cdn.lordicon.com/xyfswyxf.json"
                                                        trigger="hover"
                                                    >
                                                    </lord-icon>
                                                </span>

                                            </td>
                                        </tr>
                                    })}

                            </tbody>
                        </table>}
                </div>
            </div>
        </>
    )
}

export default Manager